server.port=8006

# PRIMARY (InMemory)
spring.datasource.url=jdbc:h2:mem:firstDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# SECONDARY (File Backup)
spring.second-datasource.url=jdbc:h2:file:./backupDB
spring.second-datasource.driver-class-name=org.h2.Driver
spring.second-datasource.username=sa
spring.second-datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

